apiVersion: v1
entries:
  welcome-api:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-02T12:53:03.891950757Z"
    description: A Helm chart for Kubernetes
    digest: 6b3e55299b14239a0c1b7e360a78ea8927fcae501ea95e05114a29ca6e13ee22
    name: welcome-api
    type: application
    urls:
    - https://lucassandin.github.io/api.welcome.github.io/charts/welcome-api-v3.tgz
    version: v3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-02T12:53:03.89147507Z"
    description: A Helm chart for Kubernetes
    digest: df28b3bec4357692c64b4a5bc3067a75afe8fc27c74e9e5f5cf3f7f47b12d3cc
    name: welcome-api
    type: application
    urls:
    - https://lucassandin.github.io/api.welcome.github.io/charts/welcome-api-v2.tgz
    version: v2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-02T12:53:03.89115362Z"
    description: A Helm chart for Kubernetes
    digest: a8417643017d38396a85e07a9639b92c351e81087cd9fc8d463af6e786e44c29
    name: welcome-api
    type: application
    urls:
    - https://lucassandin.github.io/api.welcome.github.io/charts/welcome-api-0.1.0.tgz
    version: 0.1.0
generated: "2024-05-02T12:53:03.890643609Z"
